apiVersion: v2
name: stackclass
description: Helm charts for the StackClass platform on Kubernetes
icon: https://stackclass.dev/icon.png
type: application
version: 0.23.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "16.7.18"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
