apiVersion: v2
name: stackclass
description: Helm charts for the StackClass platform on Kubernetes
icon: https://stackclass.dev/icon.png
type: application
version: 0.3.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "16.7.18"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: cert-manager
    version: "v1.18.2"
    repository: "https://charts.jetstack.io"
    condition: issuer.enabled
  - name: tekton-operator
    version: "0.76.0"
    repository: "git+https://github.com/tektoncd/operator@charts?ref=v0.76.0"
