apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: generate
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  workspaces:
    - name: source
      description: Directory to store the generated Dockerfile
  params:
    - name: COURSE_IMAGE
      description: Full path of the base image
    - name: TESTER_IMAGE
      description: Full path of the image containing test cases
  steps:
    - name: generate
      image: alpine:latest
      script: |
        cat <<EOF > $(workspaces.source.path)/Dockerfile.composite
        FROM $(params.COURSE_IMAGE) as base
        FROM $(params.TESTER_IMAGE) as second
        FROM base
        WORKDIR /app
        COPY --from=second /app /app
        COPY .stackclass/run.sh ./your_program.sh
        RUN chmod +x ./your_program.sh
        EOF
