apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
spec:
  workspaces:
    - name: context
      description: A workspace to share files for testing
    - name: docker-config
      description: Docker credentials (mounted as a Secret)
  params:
    - name: IMAGE
      description: Full path of the image to test
    - name: COMMAND
      description: Command to run for testing
      default: "echo 'Testing...'"
  steps:
    - name: test-image
      image: $(params.IMAGE)
      command: ["sh", "-c"]
      args:
        - $(params.COMMAND)
      env:
        - name: DOCKER_CONFIG
          value: $(workspaces.docker-config.path)
      volumeMounts:
        - name: docker-config
          mountPath: $(workspaces.docker-config.path)
