apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  workspaces:
    - name: source
      description: A workspace to share files for testing
    - name: dockerconfig
      description: A workspace for Docker credentials
  params:
    - name: IMAGE
      description: Full path of the image to test
    - name: COMMAND
      description: Command to run for testing
      default: "echo 'Testing...'"
    - name: TEST_CASES_JSON
      description: Test cases in JSON format
    - name: DEBUG_MODE
      description: Enable debug mode
      default: "false"
    - name: TIMEOUT_SECONDS
      description: Timeout duration in seconds
      default: "15"
    - name: SKIP_ANTI_CHEAT
      description: Skip anti-cheat checks
      default: "false"
  steps:
    - name: test-image
      image: $(params.IMAGE)
      command: ["sh", "-c"]
      args:
        - $(params.COMMAND)
      env:
        - name: DOCKER_CONFIG
          value: $(workspaces.dockerconfig.path)
        - name: STACKCLASS_REPOSITORY_DIR
          value: $(workspaces.source.path)
        - name: STACKCLASS_TEST_CASES_JSON
          value: $(params.TEST_CASES_JSON)
        - name: STACKCLASS_DEBUG
          value: $(params.DEBUG_MODE)
        - name: STACKCLASS_TIMEOUT_SECONDS
          value: $(params.TIMEOUT_SECONDS)
        - name: STACKCLASS_SKIP_ANTI_CHEAT
          value: $(params.SKIP_ANTI_CHEAT)
