apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackclass.fullname" . }}-backend-secrets
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
stringData:
  PORT: "{{ .Values.backend.service.port }}"
  REPO_DIR: "/data/repos"
  CACHE_DIR: "/data/caches"
  ALLOWED_ORIGIN: "https://{{ (index .Values.frontend.ingress.hosts 0).host }}"
  GIT_SERVER_ENDPOINT: "https://{{ (index .Values.backend.ingress.hosts 0).host }}/git"
