apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
spec:
  profile: basic
  targetNamespace: tekton-pipelines
  pipeline:
    enable-api-fields: "stable"
    performance:
      replicas: {{ .Values.tekton.pipeline.performance.replicas }}
      threads-per-controller: {{ .Values.tekton.pipeline.performance.threadsPerController }}
  chain:
    disabled: true
  result:
    disabled: true
  pruner:
    disabled: {{ .Values.tekton.pruner.disabled }}
    schedule: {{ .Values.tekton.pruner.schedule | quote }}
    startingDeadlineSeconds: 100
    resources:
      - taskrun
      - pipelinerun
    keep: {{ .Values.tekton.pruner.keep }}
    prune-per-resource: true
