{{- if .Values.frontend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stackclass.fullname" . }}-frontend
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.frontend.ingress.annotations }}
    {{- toYaml .Values.frontend.ingress.annotations | nindent 4 }}
    {{- end }}
    {{- if and .Values.frontend.ingress.tls.enabled .Values.issuer.enabled }}
    cert-manager.io/issuer: {{ include "stackclass.issuerName" . | quote }}
    {{- end }}
spec:
  {{- if .Values.global.ingressClass }}
  ingressClassName: {{ .Values.global.ingressClass }}
  {{- end }}
  rules:
    - host: {{ .Values.frontend.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "stackclass.fullname" $ }}-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
  {{- if .Values.frontend.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.frontend.ingress.host | quote }}
      secretName: {{ include "stackclass.frontendTlsName" . | quote }}
  {{- end }}
{{- end }}
