{{- if .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "stackclass.fullname" . }}-backend
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if and .Values.backend.ingress.tls.enabled (index .Values "cert-manager" "enabled") }}
    cert-manager.io/issuer: {{ (index .Values "cert-manager" "issuerRef" "name") | quote }}
  {{- end }}
spec:
  {{- if .Values.global.ingressClass }}
  ingressClassName: {{ .Values.global.ingressClass }}
  {{- end }}
  rules:
    - host: {{ .Values.backend.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "stackclass.fullname" $ }}-backend
                port:
                  number: {{ $.Values.backend.service.port }}
  {{- if .Values.backend.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.backend.ingress.host | quote }}
      secretName: {{ .Values.backend.ingress.tls.secretName | quote }}
  {{- end }}
{{- end }}
