apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "stackclass.fullname" . }}-pvc
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size | default "10Gi" }}
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass }}
  {{- end }}
