apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackclass.fullname" . }}-backend-secrets
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
type: Opaque
stringData:
  PORT: {{ .Values.backend.service.port | quote }}
  CACHE_DIR: "/data/caches"
  DATABASE_URL: {{ include "stackclass.postgresql.url" . }}
  ALLOWED_ORIGIN: {{ include "stackclass.frontend.url" . | quote }}
  GIT_SERVER_ENDPOINT: {{ .Values.backend.secrets.gitServerEndpoint | quote }}
  GIT_SERVER_USERNAME: {{ .Values.backend.secrets.gitServerUsername | quote }}
  GIT_SERVER_PASSWORD: {{ .Values.backend.secrets.gitServerPassword | quote }}
  WEBHOOK_ENDPOINT: {{ include "stackclass.backend.url" . | quote }}
  GIT_COMMITTER_NAME: {{ .Values.backend.secrets.gitCommitterName | quote }}
  GIT_COMMITTER_EMAIL: {{ .Values.backend.secrets.gitCommitterEmail | quote }}
  NAMESPACE: {{ .Release.Namespace | quote }}
  DOCKER_REGISTRY_ENDPOINT: {{ .Values.backend.secrets.dockerRegistryEndpoint | quote }}
