{{- $endpoint := .Values.backend.secrets.dockerRegistryEndpoint -}}
{{- $username := .Values.backend.secrets.dockerRegistryUsername -}}
{{- $password := .Values.backend.secrets.dockerRegistryPassword -}}
{{- $auth := printf "%s:%s" $username $password | b64enc -}}

apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
stringData:
  config.json: |
    {
      "auths": {
        "{{ $endpoint }}": {
          "auth": "{{ $auth }}"
        }
      }
    }
