apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackclass.fullname" . }}-frontend-secrets
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
type: Opaque
stringData:
  PORT: {{ .Values.frontend.service.port | quote }}
  NEXT_PUBLIC_BACKEND_URL: {{ include "stackclass.backend.url" . | quote }}
  NEXT_PUBLIC_ANALYTICS_ID: {{ .Values.frontend.secrets.analyticsId | quote }}
  BETTER_AUTH_SECRET: {{ randAlphaNum 32 | quote }}
  BETTER_AUTH_URL: {{ include "stackclass.frontend.url" . | quote }}
  BETTER_DATABASE_URL: {{ include "stackclass.postgresql.url" . }}
  GITHUB_CLIENT_ID: {{ .Values.frontend.secrets.githubClientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.frontend.secrets.githubClientSecret | quote }}
