apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackclass.fullname" . }}-frontend-secrets
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
stringData:
  PORT: "{{ .Values.frontend.service.port }}"
  NEXT_PUBLIC_BACKEND_URL: {{ include "stackclass.backend.url" . | quote }}
  BETTER_AUTH_SECRET: {{ randAlphaNum 32 | quote }}
  BETTER_AUTH_URL: {{ include "stackclass.frontend.url" . | quote }}
  BETTER_DATABASE_URL: {{ include "stackclass.postgresql.url" . }}
  GITHUB_CLIENT_ID: {{ .Values.frontend.secrets.githubClientId | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.frontend.secrets.githubClientSecret | quote }}
