{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackclass.fullname" . }}-postgresql-secrets
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
stringData:
  postgres-password: {{ randAlphaNum 16 | quote }}
  password: {{ include "stackclass.postgresql.password" . | quote }}
  replication-password: {{ randAlphaNum 16 | quote }}
{{- end }}
