{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stackclass.fullname" . }}-postgresql-secrets
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ randAlphaNum 16 | quote }}
  password: {{ include "stackclass.postgresql.password" . | quote }}
  replication-password: {{ randAlphaNum 16 | quote }}
{{- end }}
