{{- if .Values.issuer.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "stackclass.issuerName" . | quote }}
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  acme:
    email: {{ .Values.issuer.email | quote }}
    {{- if eq .Values.issuer.environment "prod" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      name: {{ printf "%s-account-key" (include "stackclass.issuerName" .) | quote }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.global.ingressClass | quote }}
{{- end }}
