{{- if .Values.issuer.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.issuer.name | quote }}
  labels:
    {{- include "stackclass.labels" . | nindent 4 }}
spec:
  acme:
    email: {{ .Values.issuer.email | quote }}
    {{- if eq .Values.issuer.environment "prod" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    privateKeySecretRef:
      name: {{ printf "%s-account-key" .Values.issuer.name | quote }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.global.ingressClass | quote }}
{{- end }}
